version: '3.8'

services:
  db_postgres:
    image: postgres:15-alpine
    container_name: bd_contabilidad
    restart: always
    environment:
      POSTGRES_USER: usuario_umb
      POSTGRES_PASSWORD: password_seguro
      POSTGRES_DB: erp_restaurante
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api_contabilidad:
    build:
      context: ./microservicio_contabilidad
    container_name: backend_contable
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db_postgres
    environment:
      DATABASE_URL: postgresql://usuario_umb:password_seguro@db_postgres:5432/erp_restaurante

  db_mongo:
    image: mongo:latest
    container_name: bd_inventario
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api_inventario:
    build:
      context: ./microservicio_inventario
    container_name: backend_inventario
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db_mongo
    environment:
      MONGO_URL: mongodb://db_mongo:27017/erp_inventario

volumes:
  postgres_data:
  mongo_data: